import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';

const ROOT = resolve(import.meta.dirname, '../../');
const CHANGELOG_PATH = resolve(ROOT, 'CHANGELOG.md');
const OUTPUT_DIR = resolve(ROOT, 'src/generated');
const OUTPUT_PATH = resolve(OUTPUT_DIR, 'changelog.ts');

const PKG_PATH = resolve(ROOT, 'package.json');

const raw = readFileSync(CHANGELOG_PATH, 'utf-8');
const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf-8')) as { version: string };

// Split by version headers, take the first one
const sections = raw.split(/(?=^## \d)/m);
const latest =
  sections.find((s) => s.startsWith('## '))?.trim() ??
  'No changelog available.';

mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
writeFileSync(
  OUTPUT_PATH,
  `// Auto-generated by scripts/generateChangelog.ts — do not edit\n/* eslint-disable */\nexport const VERSION = ${JSON.stringify(pkg.version)};\nexport const LATEST_CHANGELOG = ${JSON.stringify(latest)};\n`,
);

console.log(`Generated changelog: ${OUTPUT_PATH}`);
